version: "3.7"

services:
  ##### MongoDB #####
  mongodb:
    container_name: mongo_service
    image: mongo:4.4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=stream_tracker    
    volumes:
      - ./tmp/mongo/data/db:/data/db
    ports:
      - "27017:27017"
